/** Content search index for the docs palette. Keywords cover variants, props, and rules. */

export interface PageIndexEntry {
  id: string;
  label: string;
  group: string;
  to: string;
  keywords: string;
}

export const PAGE_INDEX: PageIndexEntry[] = [
  { id: 'home', label: 'Home', group: 'Pages', to: '/', keywords: 'start quickstart install tokens tailwind' },
  { id: 'components', label: 'All components', group: 'Pages', to: '/components', keywords: 'index directory list every' },
  { id: 'showcase', label: 'Showcase', group: 'Pages', to: '/showcase', keywords: 'all examples anchors single page' },
  { id: 'typography', label: 'Typography', group: 'Foundations', to: '/foundations/typography', keywords: 'font jakarta mono heading body muted scale type' },
  { id: 'colors', label: 'Colors', group: 'Foundations', to: '/foundations/colors', keywords: 'navy maroon status surface tint token palette blue yellow green' },
  { id: 'radius', label: 'Radius', group: 'Foundations', to: '/foundations/radius', keywords: 'rounded corner pill 8 12 16 20' },
  { id: 'icons', label: 'Icons', group: 'Foundations', to: '/foundations/icons', keywords: 'lucide emoji approved set meaning size' },
  { id: 'accordion', label: 'Accordion', group: 'Content', to: '/components/accordion', keywords: 'collapse panel faq single multiple defaultOpen' },
  { id: 'alert', label: 'Alert', group: 'Content', to: '/components/alert', keywords: 'info warning success danger tone dismissible title inline' },
  { id: 'avatar', label: 'Avatar', group: 'Viewers', to: '/components/avatar', keywords: 'photo initials fallback person size sm md lg' },
  { id: 'avatar-group', label: 'AvatarGroup', group: 'Viewers', to: '/components/avatar-group', keywords: 'people stack overflow max plus N' },
  { id: 'badge', label: 'Badge', group: 'Actions', to: '/components/badge', keywords: 'pill status tone navy grey info warning success danger icon' },
  { id: 'button', label: 'Button', group: 'Actions', to: '/components/button', keywords: 'primary secondary solid danger ghost size sm md lg loading icon click' },
  { id: 'card', label: 'Card', group: 'Content', to: '/components/card', keywords: 'panel padding none md lg surface' },
  { id: 'checkbox', label: 'Checkbox', group: 'Forms', to: '/components/checkbox', keywords: 'multi select check description disabled native' },
  { id: 'radio', label: 'Radio', group: 'Forms', to: '/components/radio', keywords: 'single select group name option disabled native' },
  { id: 'switch', label: 'Switch', group: 'Forms', to: '/components/switch', keywords: 'toggle on off instant apply checked disabled navy' },
  { id: 'carousel', label: 'Carousel', group: 'Content', to: '/components/carousel', keywords: 'slide dots arrows autoplay interval pause hover' },
  { id: 'bar', label: 'Bar', group: 'Charts', to: '/components/charts/bar', keywords: 'chart column legend toggle height svg' },
  { id: 'line', label: 'Line', group: 'Charts', to: '/components/charts/line', keywords: 'chart area dots series tooltip multi legend points' },
  { id: 'pie', label: 'Pie', group: 'Charts', to: '/components/charts/pie', keywords: 'chart donut hole slice share legend size' },
  { id: 'scatter', label: 'Scatter', group: 'Charts', to: '/components/charts/scatter', keywords: 'chart dot plot series tooltip axis domain' },
  { id: 'heatmap', label: 'Heatmap', group: 'Charts', to: '/components/heatmap', keywords: 'chart intensity grid cell axis order select' },
  { id: 'treemap', label: 'Treemap', group: 'Charts', to: '/components/charts/treemap', keywords: 'chart rectangle squarified area share select' },
  { id: 'wordcloud', label: 'WordCloud', group: 'Charts', to: '/components/charts/wordcloud', keywords: 'chart words weight cloud drag deterministic select' },
  { id: 'code-block', label: 'CodeBlock', group: 'Viewers', to: '/components/code-block', keywords: 'snippet language copy bare height scroll' },
  { id: 'combobox', label: 'Combobox', group: 'Forms', to: '/components/combobox', keywords: 'picker searchable filter keyboard options value helper error' },
  { id: 'command-palette', label: 'CommandPalette', group: 'Overlays', to: '/components/command-palette', keywords: 'command ctrl k fuzzy group keyboard enter escape' },
  { id: 'copy-button', label: 'CopyButton', group: 'Actions', to: '/components/copy-button', keywords: 'clipboard copy check confirm size callback' },
  { id: 'date-picker', label: 'DatePicker', group: 'Forms', to: '/components/date-picker', keywords: 'calendar date iso min max locale drill month year keyboard' },
  { id: 'drawer', label: 'Drawer', group: 'Overlays', to: '/components/drawer', keywords: 'panel side left right focus trap escape overlay footer' },
  { id: 'dropdown', label: 'Dropdown', group: 'Overlays', to: '/components/dropdown', keywords: 'menu trigger flyout nested danger item select' },
  { id: 'empty-state', label: 'EmptyState', group: 'Data', to: '/components/empty-state', keywords: 'empty nothing action icon title description' },
  { id: 'file-upload', label: 'FileUpload', group: 'Forms', to: '/components/file-upload', keywords: 'dropzone browse accept size limit files validation' },
  { id: 'file-viewer', label: 'FileViewer', group: 'Viewers', to: '/components/file-viewer', keywords: 'file code lines numbers language copy height filename' },
  { id: 'graph-viewer', label: 'GraphViewer', group: 'Charts', to: '/components/graph-viewer', keywords: 'graph nodes edges pan zoom select legend group layout' },
  { id: 'image', label: 'Image', group: 'Viewers', to: '/components/image', keywords: 'picture aspect fallback skeleton rounded alt cover' },
  { id: 'input', label: 'Input', group: 'Forms', to: '/components/input', keywords: 'text field label helper error icon placeholder focus' },
  { id: 'select', label: 'Select', group: 'Forms', to: '/components/select', keywords: 'dropdown native option label helper error fixed list' },
  { id: 'textarea', label: 'Textarea', group: 'Forms', to: '/components/textarea', keywords: 'multiline rows label helper error resize' },
  { id: 'kbd', label: 'Kbd', group: 'Content', to: '/components/kbd', keywords: 'keyboard key shortcut chip mono ctrl esc' },
  { id: 'log-viewer', label: 'LogViewer', group: 'Content', to: '/components/log-viewer', keywords: 'log level debug info success warn error filter follow copy clear mono' },
  { id: 'markdown', label: 'Markdown', group: 'Content', to: '/components/markdown', keywords: 'gfm docs table fence code source' },
  { id: 'modal', label: 'Modal', group: 'Overlays', to: '/components/modal', keywords: 'dialog confirm delete maroon trash focus trap escape overlay size sm md lg xl footer' },
  { id: 'navbar', label: 'Navbar', group: 'Navigation', to: '/components/navbar', keywords: 'top bar brand links active actions dropdown' },
  { id: 'pagination', label: 'Pagination', group: 'Data', to: '/components/pagination', keywords: 'page prev next ellipsis window note count' },
  { id: 'progress', label: 'Progress', group: 'Charts', to: '/components/progress', keywords: 'bar percent determinate indeterminate tone label' },
  { id: 'search-bar', label: 'SearchBar', group: 'Navigation', to: '/components/search-bar', keywords: 'search filter clear escape shortcut hint query' },
  { id: 'sidebar', label: 'Sidebar', group: 'Navigation', to: '/components/sidebar', keywords: 'nav menu collapse rail submenu nested active icon' },
  { id: 'breadcrumbs', label: 'Breadcrumbs', group: 'Navigation', to: '/components/breadcrumbs', keywords: 'trail hierarchy chevron home link current' },
  { id: 'skeleton', label: 'Skeleton', group: 'Data', to: '/components/skeleton', keywords: 'loading placeholder pulse width height shape' },
  { id: 'slider', label: 'Slider', group: 'Forms', to: '/components/slider', keywords: 'range number min max step value volume disabled' },
  { id: 'spinner', label: 'Spinner', group: 'Charts', to: '/components/spinner', keywords: 'loading wait size label status button' },
  { id: 'stepper', label: 'Stepper', group: 'Navigation', to: '/components/stepper', keywords: 'steps wizard progress current vertical clickable' },
  { id: 'submenu-bar', label: 'SubmenuBar', group: 'Navigation', to: '/components/submenu-bar', keywords: 'strip tabs count indicator section' },
  { id: 'table', label: 'Table', group: 'Data', to: '/components/table', keywords: 'rows columns sort filter select skeleton empty pagination key' },
  { id: 'tabs', label: 'Tabs', group: 'Navigation', to: '/components/tabs', keywords: 'switch views arrow keys disabled indicator controlled' },
  { id: 'timeline', label: 'Timeline', group: 'Content', to: '/components/timeline', keywords: 'feed events dots tone time history' },
  { id: 'timing-bar', label: 'TimingBar', group: 'Charts', to: '/components/timing-bar', keywords: 'stacked duration segments legend total unit ms' },
  { id: 'toast', label: 'Toast', group: 'Overlays', to: '/components/toast', keywords: 'notification provider info warning success danger duration title dismiss' },
  { id: 'tooltip', label: 'Tooltip', group: 'Overlays', to: '/components/tooltip', keywords: 'hover hint position delay top bottom left right' },
  { id: 'tree-view', label: 'TreeView', group: 'Content', to: '/components/tree-view', keywords: 'tree files expand select arrow nested folder' },
];
