/**
 * Canonical OmegaOS icon list. Every name must resolve to a lucide-react
 * export (see `iconComponentName`). Icons render at 16px in buttons,
 * 18px in headings, 12px in badges. Never use emoji.
 */
export const OMEGA_ICONS = [
  'crown',
  'layout-dashboard',
  'home',
  'folder',
  'layers',
  'terminal',
  'command',
  'globe',
  'book-open',
  'plus',
  'minus',
  'x',
  'check',
  'pencil',
  'trash-2',
  'copy',
  'download',
  'upload',
  'save',
  'search',
  'filter',
  'settings',
  'more-horizontal',
  'external-link',
  'arrow-right',
  'arrow-left',
  'chevron-down',
  'chevron-up',
  'chevron-left',
  'chevron-right',
  'refresh-cw',
  'rotate-ccw',
  'play',
  'eye',
  'eye-off',
  'user',
  'users',
  'user-plus',
  'mail',
  'lock',
  'key',
  'fingerprint',
  'tag',
  'calendar',
  'clock',
  'history',
  'info',
  'triangle-alert',
  'octagon-x',
  'shield',
  'shield-check',
  'shield-alert',
  'circle-check',
  'loader-2',
  'bell',
  'ban',
  'log-out',
  'power',
  'sun',
  'moon',
  'file',
  'file-text',
  'files',
  'code',
  'image',
  'link',
  'bookmark',
  'github',
  'git-branch',
  'monitor',
  'cpu',
  'activity',
  'database',
  'server',
  'cloud',
  'wifi',
  'siren',
  'wrench',
  'hammer',
  'package',
  'rocket',
  'send',
  'inbox',
  'archive',
  'star',
  'pin',
  'share-2',
  'sliders-horizontal',
  'list',
  'squircle',
  'table',
  'panel-top',
  'panel-left',
] as const;

export type OmegaIconName = (typeof OMEGA_ICONS)[number];

/** Converts a kebab-case icon name to its lucide-react export, e.g. `trash-2` → `Trash2`. */
export function iconComponentName(name: string): string {
  return name
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}
